# Generated by Django 4.0.4 on 2022-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('type', models.CharField(choices=[('Expenses', 'Expenses'), ('Income', 'Income')], max_length=8)),
            ],
        ),
    ]
